version: '3.3'
services:
  packet-storm:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./
    hostname: m0rgu3_w1tch
    tty: true
    stdin_open: true
    entrypoint: '/usr/bin/python3 packet-storm-cli.py'

