version: '3.3'
services:
  packet-storm:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./
    container_name: packet-storm
    volumes:
      - ./docs/Cybersecurity:/packet-storm-cli/docs/Cybersecurity
    tty: true
    stdin_open: true
    entrypoint: '/usr/bin/python3 packet-storm-cli.py -ed docs/Cybersecurity'