name: Packet Storm CI

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
#    - uses: actions/checkout@master
    - name: Export glossary notes to TXT format
      shell: bash
      run: |
        cd packet-storm/,
        cd documentation/,
        /bin/bash ./export.sh.
