name: Packet Storm CI

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install essentials
      shell: bash
      run: |
        sudo apt update
        sudo apt install xvfb -y
        wget https://launchpad.net/~giuspen/+archive/ubuntu/ppa/+files/cherrytree_0.99.46-1_amd64.deb -O cherrytree.deb
        sudo dpkg -i cherrytree.deb
    - name: Export glossary notes to TXT format
      shell: bash
      run: /home/runner/work/packet-storm/packet-storm/documentation/export.sh pentest-notizen.ctb
