name: Packet Storm CI

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Export glossary notes to TXT format
      run: |
        ls -la,
        /bin/bash ./export.sh.